config/routes.rb
Rails.application.routes.draw do

  resources :items do
    collection do
      get 'search'
    end
    resources :trades, only: [:new, :create]
  end
  resources :items, only: %i(index show new) do
  end
  root 'items#index'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :profiles, only: [:index, :show, :edit, :new] do
    collection do
      get 'logout'
      get 'registration_creditcard'
      get 'credit2'
  end
end

  namespace :admin do
    resources :users, only: [:index,:show]
  end

  resources :registrations,only: :new

  resources :categories,only: :index

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :name,         presence: true, length: { maximum: 20 }
  validates :nickname,     presence: true, length: { maximum: 20 }
  validates :birthdate,    presence: true
  validates :postal_code,  presence: true
  validates :prefecture,   presence: true
  validates :municipality, presence: true
  validates :block,        presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end

  def logout
    @crumb_name = "ログアウト"
  end

  def registration_creditcard
    @crumb_name = "クレジットカード登録"
  end

  def credit2
  end


end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_l-side.html.haml
.l-side
  .naviBar
    %ul.naviBar__naviList
      = link_to profiles_path do
        %li.naviBar__naviList__Item
          マイページ
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          お知らせ
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          やることリスト
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          いいね！一覧
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          出品する
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          出品した商品 - 出品中
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          出品した商品 - 取引中
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          出品した商品 - 売却済み
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          購入した商品 - 取引中
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          購入した商品 - 過去の取引
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          ニュース一覧
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          評価一覧
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          ガイド
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          お問い合わせ
          %i.fas.fa-chevron-right
    %h3.naviBar__naviHead メルペイ
    %ul.naviBar__naviList
      = link_to do
        %li.naviBar__naviList__Item
          売上・振込申請
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          ポイント
          %i.fas.fa-chevron-right
    %h3.naviBar__naviHead 設定
    %ul.naviBar__naviList
      = link_to profile_path(current_user.id) do
        %li.naviBar__naviList__Item
          プロフィール
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          支払い方法
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          メール/パスワード
          %i.fas.fa-chevron-right
      = link_to edit_profile_path(current_user.id) do
        %li.naviBar__naviList__Item
          本人情報
          %i.fas.fa-chevron-right
      = link_to do
        %li.naviBar__naviList__Item
          電話番号の確認
          %i.fas.fa-chevron-right
      = link_to logout_profiles_path do
        %li.naviBar__naviList__Item
          ログアウト
          %i.fas.fa-chevron-right

app/views/profiles/_notification-todo.html.haml
.notificationTodo
  %ul.notificationTodo__mypageTabs
    = link_to do
      %li.info
        お知らせ
    = link_to do
      %li.todo
        やることリスト
  .notificationTodo__tabContent
    %ul.notificationTodo__tabContent__notification
    %ul.notificationTodo__tabContent__todo
      %li.notFoundTab
        現在、やることリストはありません

app/views/profiles/_purchased.html.haml
.purchased
  %h2.purchased__tabHead
    購入した商品
  %ul.purchased--mypageTabs
    = link_to do
      %li.purchased--mypageTabs__enRoute
        取引中
    = link_to do
      %li.purchased--mypageTabs__settled
        過去の取引
  .purchased--tabContent
    %ul.purchased--tabContent__transactionNow
      %li.transactionNotFound
        取引中の商品がありません
    %ul.purchased--tabContent__transactionOld

app/views/profiles/credit2.html.haml
= render "items/header"

.main-content
  .l-container.clearfix
    .l-content
      .l-chapter
        %section.l-chapter__container1
          %h2.l-chapter__head 支払い方法
          .l-chapter__inner
            %section
              .l-chapter__content
                %h3.l-chapter__credit--text クレジットカード一覧
                %ul.l-chapter__settings-payment-list
                  %li.l-chapter__creditlist
                    %form.l-chapter__creditcard
                      %figure
                        = image_tag("credit_logo/visa_logo.svg",class:'l-chapter__vasalogo')
                      .l-chapter__creditnumber **************
                      .l-chapter__creditdate **/**
                      %button.l-chapter__button{:type => "submit"} 削除する
          .l-chapter__footer
            %a.l-chapter__cash{href:"#"}
              %span.l-chapter__back 支払い方法について＞
    = render "l-side"

= render "items/footer"

app/views/profiles/edit.html.haml
.main-content
  = render 'items/header'
  .l-container.clearfix
    .l-content
      .personalInfomation
        %h2.personalHead 本人情報の登録
        %form.personalBody{action: "", method: "POST", novalidate: ""}
          .confirmation-info
            %p.confirmation-info__description
              お客さまの本人情報をご登録ください。
              %br>/
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p.confirmation-info__descriptionDetail
              = link_to "本人確認書類のアップロードについて" , class: "upload"
              %i.fas.fa-chevron-right
          .formBoard
            .formBoard__formHead お名前
            .formBoard__formItem 手苦 駅酢派後
          .formBoard
            .formBoard__formHead お名前カナ
            .formBoard__formItem テック エキスパート
          .formBoard
            .formBoard__formHead{for: "birthday"} 生年月日
            .formBoard__formItem 2019/01/12
          .formBoard
            .formBoard__formHead{for: "postal_code"} 郵便番号
            %span.formBoard__arbitrary 任意
            %input.formBoard__inputDefault{name: "zip_code", placeholder: "例）5420081", type: "text", value: ""}/
          .formBoard
            .formBoard__formHead{for: "prefecture"} 都道府県
            %span.formBoard__arbitrary 任意
            .formBoard__selectWrap
              %select.formBoard__selectWrap--prefecture{name: "prefecture"}
                %option 東京
                %option 大阪府
              %i.formBoard__selectWrap.fas.fa-chevron-down
          .formBoard
            .formBoard__formHead{for: "city"} 市区町村
            %span.formBoard__arbitrary 任意
            %input.formBoard__inputDefault{name: "city", placeholder: "例) 大阪市中央区", type: "text", value: ""}/
          .formBoard
            .formBoard__formHead{for: "address1_label"} 番地
            %span.formBoard__arbitrary 任意
            %input.formBoard__inputDefault{name: "address1", placeholder: "例) 南船場2-6-28", type: "text", value: ""}/
          .formBoard
            .formBoard__formHead{for: "address2_label"} 建物名
            %span.formBoard__arbitrary 任意
            %input.formBoard__inputDefault{name: "address2", placeholder: "例) ユタカビル7階", type: "text", value: ""}/
          %button.btnRegist{type: "submit"} 登録する
          .confirmation-info.another
            %p.confirmation-info__descriptionDetail
              = link_to "本人情報の登録について" , class: "regist"
              %i.fas.fa-chevron-right
          %input.personalData{type: "hidden", value: ""}/
    = render 'l-side'
  = render 'items/footer'

app/views/profiles/index.html.haml
.main-content
  = render 'items/header'
  = render "items/breadcrumbs-profiles"
  .l-container.clearfix
    .l-content
      .mypageUserIcon
        = link_to(class: "profileLink") do
          .profileLink__figureImage
            = image_tag("//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png", width: "60", class: "avator_image")
          .profileLink__userName
            ユーザーネーム
          .profileLink__mypageCount
            .profileLink__mypageCount__evaluation
              評価
              .evaluationCount.bold
                0
            .profileLink__mypageCount__listingNumber
              出品数
              .listingNumberCount.bold
                0
      = render 'notification-todo'
      = render 'purchased'
    = render 'l-side'
  = render 'items/footer'

app/views/profiles/logout.html.haml
.main-content
  = render partial: "items/header"
  = render "items/breadcrumbs-profile"
  .l-container.clearfix
    .l-content
      .l-chapter__inner
        .l-chapter__content
          .button.l-chapter__logout
            =link_to'ログアウト', destroy_user_session_path, method: :delete,:class => 'l-chapter__logout-text--button'
    = render partial: "l-side"
= render partial: "items/footer"

app/views/profiles/new.html.haml
= render "items/header"

.main-content
  .l-container.clearfix
    .l-content
      .l-chapter
        %section.l-chapter__container1
          %h2.l-chapter__head 支払い方法
          .l-chapter__inner
            %section
              .l-chapter__content
                %h3.l-chapter__credit--text クレジットカード一覧
                %ul.l-chapter__settings-payment-list
                  %li.l-chapter__creditlist
                    %form.l-chapter__creditcard
                      %figure
                        %img{:alt => "visa", :height => "15", :src => "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2845599746", :width => "49"}
                      .l-chapter__creditnumber **************
                      .l-chapter__creditdate **/**
                      %button.l-chapter__button{:type => "submit"} 削除する
          .l-chapter__footer
            %a.l-chapter__cash{href:"#"}
              %span.l-chapter__back 支払い方法について＞
    = render "l-side"

= render "items/footer"

app/views/profiles/registration_creditcard.html.haml
.main-content
  = render "items/header"
  = render "items/breadcrumbs-profile"
  / profiles
  / - breadcrumb :profiles
  / = breadcrumbs separator: " &rsaquo; "

  / categories
  / - breadcrumb :categories
  / = breadcrumbs separator: " &rsaquo; ", class: 'a', current_class: 'b'

  / profile
  / - breadcrumb :profile, @crumb_name
  / = breadcrumbs separator: " &rsaquo; "

  / categorie
  / - breadcrumb :categorie, @categorie
  / = breadcrumbs separator: " &rsaquo; "

  .l-container.clearfix
    .l-content
      %h2.l-content__credithead クレジットカード情報入力
      .l-content__form-all
        .l-content__editingscreen
          .form-group
            %label.form-group__toptext カード番号
            %span.form-group__form-require 必須
            %input#payment_card_no.form-group__input-default{"data-input-type" => "card", :maxlength => "19", :placeholder => "半角数字のみ", :type => "text", :value => ""}/
            %ul.form-group__signup-card-logo
              %li
                = image_tag("credit_logo/visa_logo.svg",class:'form-group__signup-card-logo--visa')
              %li
                = image_tag("credit_logo/master-card.svg",class:'form-group__signup-card-logo--master')
              %li
                = image_tag("credit_logo/saison-card.svg",class:'form-group__signup-card-logo--saison')
              %li
                = image_tag("credit_logo/jcb.svg",class:'form-group__signup-card-logo--jcb')
              %li
                = image_tag("credit_logo/american_express.svg",class:'form-group__signup-card-logo--american')
              %li
                = image_tag("credit_logo/dinersclub.svg",class:'form-group__signup-card-logo--dinersclub')
              %li
                = image_tag("credit_logo/discover.svg",class:'form-group__signup-card-logo--discover')
          .form-group
            .form-group__expiration_date
            %label.form-group__toptext{:for => "payment_card_expire"} 有効期限
            %span.form-group__form-require 必須
            %br/
            .form-group__expiration_date_monthyear
              %select#payment_card_expire_mm.form-group__expiration_date_monthyear--select-default
                %option{:value => "01"} 01
                %option{:value => "02"} 02
                %option{:value => "03"} 03
                %option{:value => "04"} 04
                %option{:value => "05"} 05
                %option{:value => "06"} 06
                %option{:value => "07"} 07
                %option{:value => "08"} 08
                %option{:value => "09"} 09
                %option{:value => "10"} 10
                %option{:value => "11"} 11
                %option{:value => "12"} 12
              %i.icon-arrow-bottom
            %span.form-group__monthyeartext 月
            %ul#expire-mm-error-wrapper.has-error-text
            .form-group__expiration_date_monthyear
              %select#payment_card_expire_yy.form-group__expiration_date_monthyear--select-default
                %option{:value => "19"} 19
                %option{:value => "20"} 20
                %option{:value => "21"} 21
                %option{:value => "22"} 22
                %option{:value => "23"} 23
                %option{:value => "24"} 24
                %option{:value => "25"} 25
                %option{:value => "26"} 26
                %option{:value => "27"} 27
                %option{:value => "28"} 28
                %option{:value => "29"} 29
              %i.icon-arrow-bottom
            %span.form-group__monthyeartext 年
          .form-group
            %label.form-group__toptext セキュリティコード
            %span.form-group__form-require 必須
            %input#payment_card_security_code.form-group__input-default{:placeholder => "カード背面4桁もしくは3桁の番号", :type => "number", :value => ""}/
            %ul#security-code-error-wrapper.has-error-text
            .signup-seqcode
              .form-group__signup-seqcode-text
                %span.form-group__form-question> ?
                カード裏面の番号とは？
          %button#submit-button.form-group__btn-default.btn-red{:type => "button"} 追加する
    = render "l-side"
= render "items/footer"

app/views/profiles/show.html.haml
.main-content
  = render 'items/header'
  .l-container.clearfix
    .l-content
      .profileboard
        %h2.boardhead プロフィール
        %form.boardform{action: "", method: "POST"}
          .boardform__namecard
            .boardform__namecard--profileicon
              = image_tag("//static.mercdn.net/images/member_photo_noimage_thumb.png", size: "60x60")
            %input.boardform__namecard--namespace{name: "nickname", placeholder: "例)ニックネームorタイトル", type: "text", value: ""}/
          .boardform__profilecontent
            %textarea.boardform__profilecontent--bulletin{name: "introduction", placeholder: "例）取扱商品とか人物紹介とか連絡方法とかとか"}
            %button.boardform__profilecontent--changebtn{type: "submit"} 変更する
    = render 'l-side'
  = render 'items/footer'