config/routes.rb
Rails.application.routes.draw do

  resources :items do
    collection do
      get 'search'
    end
    resources :trades, only: [:new, :create]
  end
  resources :items, only: %i(index show new) do
  end
  root 'items#index'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :profiles, only: [:index, :show, :edit, :new] do
    collection do
      get 'logout'
      get 'registration_creditcard'
      get 'credit2'
  end
end

  namespace :admin do
    resources :users, only: [:index,:show]
  end

  resources :registrations,only: :new

  resources :categories,only: :index

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_one_attached :avatar
  has_one :trade
  belongs_to :user

  validates :avatar,                  presence: true
  validates :name,                    presence: true
  validates :status,                  presence: true

  validates :price,                   numericality: {
                                       only_integer: true,
                                       greater_than: 0,
                                       less_than: 1000000 }
  validates :delivery_charge_burden,  presence: true
  validates :days_up_to_delivery,     presence: true
  validates :prefecture,              presence: true
  validates :description,             presence: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_target_item, only: %i[show destroy]
  before_action :set_update_item, only: %i[edit update]
  def index
  	@items = Item.all.order('id DESC').limit(4)
  end

  def show
    @item = Item.find(params[:id])
    @others = Item.where(user_id: @item.user_id).where.not(id: @item.id).order("RAND()").limit(6)
  end

  def new
    @item = Item.new
  end

  def search
  	 @items = Item.where('name LIKE(?)', "%#{params[:keyword]}%").limit(40)
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: "「#{@item.name}」を出品しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to action: "show", notice: "「#{@item.name}」を編集しました"
    else
      render :edit
    end
  end

  def destroy

    unless @item.user_id == current_user.id
      redirect_to items_path, notice: "出品者でないため削除できません"
    else
      if @item.destroy
        redirect_to items_path, notice: "「#{@item.name}」を削除しました"
      else
        render :show
      end
    end

  end

  private

  def item_params
    params.require(:item).permit(:avatar,
                                 :name,
                                 :description,
                                 :category_id,
                                 :status,
                                 :delivery_charge_burden,
                                 :prefecture,
                                 :days_up_to_delivery,
                                 :price).merge(user_id: current_user.id)
  end

  def set_target_item
    @item = Item.find(params[:id])
  end

  def set_update_item
    @item = current_user.items.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_breadcrumbs-item.html.haml
- breadcrumb :item, @item
= breadcrumbs separator: " &rsaquo; ", current_class: 'crumb-name'

app/views/items/_breadcrumbs-items-map.html.haml
- breadcrumb :items_map
= breadcrumbs separator: " &rsaquo; ", current_class: 'crumb-name'

app/views/items/_breadcrumbs-profile.html.haml
- breadcrumb :profile, @crumb_name
= breadcrumbs separator: " &rsaquo; ", current_class: 'crumb-name'

app/views/items/_breadcrumbs-profiles.html.haml
- breadcrumb :profiles, @crumb_name
= breadcrumbs separator: " &rsaquo; ", current_class: 'crumb-name'

app/views/items/_footer.html.haml
.footer
  .footer__top_banner
    .footer__top_banner__mobile
    %p.footer__top_banner__message
    .mercari_logo_bottom
    .apple_logo_bottom
      / = image_tag "top_image/app-store.svg", class: 'apple_logo_bottom'
    .google_logo_bottom
      / = image_tag "top_image/google-play.svg"
  .footer__bottom__banner
    .footer__bottom__banner__about_mercari
      %p 会社概要（運営会社)
      %p プライバシーポリシー
      %p メルカリ利用規約
      %p 有償ポイントに関する特約
      %p あんしんスマホサポート制度に関する利用特約
      %p コンプライアンスポリシー
      %p 個人データの安全管理に係る基本方針
      %p 特定商取引に関する表記
      %p 資金決済法に基づく表示
      %p 法令順守と犯罪抑止のために
      %p 採用情報
    .footer__bottom__banner__show_mercari
      %p メルカリを見る
      %p カテゴリー一覧
      %p ブランド一覧
      %p 出品地域一覧
      %p 公式ブログ
      %p 公式Twitter
      %p 公式Facebook
    .footer__bottom__banner__help_guide_mercari
      %p ヘルプ＆ガイド
      %p メルカリガイド
      %p メルカリロゴ利用ガイドライン
      %p お知らせ
      %p らくらくメルカリ便とは
      %p ゆうゆうメルカリ便とは
      %p 大型らくらくメルカリ便とは
      %p 車体取引ガイド
      %p 返品・返金ポリシー
      %p メルカリあんしん・あんぜん宣言！
      %p 偽ブランド品撲滅への取り組み
      %p メルカリボックス
    .footer__bottom__banner__country_mercari
      %p 国
      %p United States
      %p United Kingdom
      %p 日本
  .mercai_2019
.sell_btn
  %p.sell_btn__message
    出品
  =link_to new_item_path do
    %i.fas.fa-camera

app/views/items/_header.html.haml
%header
  .header__mercari
    = link_to root_path do
      = image_tag "top_image/logo.svg", class: 'mercari_logo'
    = form_tag('/items/search', method: :get, class: 'search', name: 'form') do
      %input.mercari-header{:name => "keyword", :placeholder => "キーワードから探す", :type => "text", :value => ""}/

  .header__navi
    .header__navi__left
      = link_to "カテゴリーから探す", categories_path, class: 'left'
      %p.left ブランドから探す
    .header__navi__right
    -if user_signed_in?
      = image_tag "top_image/member_photo_noimage_thumb.png", class: 'mypage_logo'
      = link_to "マイページ", profiles_path, class: 'right'
      %i.far.fa-bell
      %p.right お知らせ
      %i.fas.fa-check
      %p.right やることリスト
    -else
      .header__navi__button-box
      = link_to user_session_path, class: 'underline-kill' do
        .header__navi__Log-In
          ログイン
      = link_to new_user_registration_path, class: 'underline-kill' do
        .header__navi__sign-up
          新規登録

app/views/items/_individual.html.haml
.individual_item_container{"dataItem_id": @item.id}
  .individual_item_container__item_name
    = @item.name
  .individual_item_container__item_flex
    .individual_item_container__item_image
      - if @item.trade.present?
        .contents_image_box--redTryangle
          .contents_image_box--redTryangle__textSold sold
      = image_tag @item.avatar, class: "showImg", size: "270x270"
    %table
      %tr.exhibitor
        %th.exhibitor 出品者
        %td.exhibitor
          = @item.user.profile.name
          %i.fas.fa-smile-beam 5
          %i.fas.fa-meh 5
          %i.fas.fa-sad-tear 5

      %tr.category
        %th.category カテゴリー
        %td.category
          = @item.id
      %tr.show
        %th.show ブランド
        %td.show
          = @item.brand_id
      %tr.show
        %th.show 商品の状態
        %td.show
          = @item.status
      %tr.show
        %th.show 配送料負担
        %td.show
          = @item.delivery_charge_burden
      %tr.ligion
        %th.ligion 配送地域
        %td.ligion
          = @item.prefecture
      %tr.show
        %th.show 配送日の目安
        %td.show
          = @item.days_up_to_delivery

  .individual_item_container__item_price ¥ #{ @item.price.to_s(:delimited) } (税込)
  .individual_item_container__item_burden
    = @item.delivery_charge_burden
  .itemButtonBox
    - if @item.trade.present?
      .individual_item_container__item_button.soldOut 売り切れてしまいました
    - if @item.trade.blank? && current_user != @item.user
      = link_to new_item_trade_path(@item.id) do
        .individual_item_container__item_button 購入画面に進む
  .individual_item_container__item_description
    %p #{ @item.description }
    .individual_item_container__box
      .individual_item_container__box__like_button
        %i.far.fa-heart いいね！
      .individual_item_container__box__report_button
        %i.far.fa-flag  不適切な商品の報告
      .individual_item_container__box__message
        %i.fas.fa-lock あんしん・あんぜんへの取り組み
  - if current_user == @item.user && @item.trade.blank?
    .itemShow-container
      = link_to edit_item_path do
        .individual_item_container__item_button 編集する
      = link_to item_path, method: :delete, data: { confirm: '削除しますか？' } do
        .individual_item_container__item_button 削除する

app/views/items/edit.html.haml
.main-content
  = render "/registrations/registration-header"
  .item-content-area
    .item-content-area__text 商品の情報を入力
    = form_with model: @item, local: true do |f|
      // 出品画像
      .item-image.box
        .item-box-header
          %span.item-box-header__big-title 出品画像
          %span.item-box-header__must-icon 必須
        .item-image__infomation
          最大10枚までアップロードできます
        .item-image__uploadarea
          = f.file_field :avatar, style: "display: none", class: "image-upload", id: "image-upload"
          .item-image__uploadarea-text{onClick: "$('#image-upload').click();"}
            %p.image-message ドラッグアンドドロップ
            %p.image-message またはクリックしてファイルをアップロード

      // 商品名
      .item-data.box
        .item-box-header
          %span.item-box-header__small-title 商品名
          %span.item-box-header__must-icon 必須
        = f.text_field :name, class: "item-data__name text-field", placeholder: "商品名(必須 40文字まで)"
        .item-box-header__next
          %span.item-box-header__small-title 商品説明
          %span.item-box-header__must-icon 必須
        = f.text_area :description, class: "item-data__detail text-area", placeholder: "商品の説明（1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

      // 商品の詳細
      .item-detail.box.flexbox
        .left-side 商品の詳細
        .right-side
          .item-box-header
            %span.item-box-header__small-title カテゴリー
            %span.item-box-header__must-icon 必須
          = f.select :category_id, [ 1, 2, 3, 4], {}, {class: "item-detail__category select-field"}
          .item-box-header__next
            %span.item-box-header__small-title 商品の状態
            %span.item-box-header__must-icon 必須
          = f.select :status, ["---", "新品、未使用", "未使用に近い", "目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"], {}, {class: "item-detail__status select-field"}

      // 配送詳細
      .item-delivery.box.flexbox
        .left-side 配送について
        .right-side
          .item-box-header
            %span.item-box-header__small-title 配送料の負担
            %span.item-box-header__must-icon 必須
          = f.select :delivery_charge_burden, ["---", "送料込み(出品者負担)", "着払い(購入者負担)"], {}, {class: "item-delivery__fee select-field"}
          .item-box-header__next
            %span.item-box-header__small-title 発送元の地域
            %span.item-box-header__must-icon 必須
          = f.select :prefecture, ["---", "ここは後日active_hash"], {}, {class: "item-delivary__area select-field"}
          .item-box-header__next
            %span.item-box-header__small-title 発送までの日数
            %span.item-box-header__must-icon 必須
          = f.select :days_up_to_delivery, ["---","1〜2日で発送","2〜3日で発送","4〜7日で発送"], {}, {class: "item-delivary__days select-field"}
      // 料金
      .item-price.box.flexbox
        .left-side
          %span 販売価格(300〜9,999,999)
          %span.fas.fa-question-circle.blue-icon
        .right-side
          .right-side-first.flexbox.pad-1
            .right-side-left
              .item-box-header
                %span.item-box-header__small-title 価格
                %span.item-box-header__must-icon 必須
            .right-side-right
              %span.yen-mark ¥
              = f.text_field :price, placeholder: "例）300", class: "item-price__sell text-field text-field__mini"
          .right-side-second.flexbox.pad-2.bar
            .right-side-left
              %p.fee 販売手数料(10%)
            .right-side-right
              .show-tax -
          .right-side-third.flexbox.pad-2.bar
            .right-side-left
              %p.profit.bold 販売利益
            .right-side-right
              .show-profit.bold -

      // 注意書きと出品ボタン
      .attention.box
        .attention-text
          .attention
            %p.attention-1
              = link_to "禁止されている出品", "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/", class: "no-line"
              、
              = link_to "行為", "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/", class: "no-line"
              を必ずご確認ください。
            %p.attention-2
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "偽ブランドの販売", "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/", class: "no-line"
              は犯罪であり処罰される可能性があります。
            %p.attention-3
              また、出品をもちまして
              = link_to "加盟店規約", "https://www.mercari.com/jp/seller_terms/", class: "no-line"
              に同意したことになります。
        = f.submit "変更する", class: "listing-btn"
        .return-area
          = link_to item_path do
            .return-btn
              もどる


  = render "/registrations/registration-footer"

app/views/items/index.html.haml
.default-container
  = render 'header'
.top_banner#slide-top-banner
  .slider-wrapper
    = image_tag "top_image/1.jpg",class: 'top_banner__main_image'
    = image_tag "top_image/2.jpg",class: 'top_banner__main_image'
    = image_tag "top_image/3.jpg",class: 'top_banner__main_image'

.pickup_container
  %h3.pickup_container__message
    ピックアップアイテム
  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      レディース新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4


  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      メンズ新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4

  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      ベビーキッズ新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4

  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      コスメ・香水・美容新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4

.pickup_container
  %h3.pickup_container__message
    ピックアップブランド
  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      シャネル新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4

  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      ルイ・ヴィトン新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4

  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      シュプリーム新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4

  .new_pickup__category
    %p.new_pickup__category__ladies_new__message
      ナイキ新着アイテム
      .new_pickup__category__new
        - @items.each do |item|
          .new_pickup__category__new__contents_box
            .new_pickup__category__new-image
              = link_to item_path(item), method: :get do
                = image_tag item.avatar, :class => "thumnail-box"
              .item_box_body
                .item_box_body__name
                  = item.name
                .item_box_body__num
                  .item_box_body__num__price
                    = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                  .item_box_body__num__tax (税込)
                  %i.far.fa-heart 4

= render 'footer'

app/views/items/new.html.haml
.main-content
  = render "/registrations/registration-header"
  .item-content-area
    .item-content-area__text 商品の情報を入力
    = form_with model: @item, local: true do |f|
      // 出品画像
      .item-image.box
        .item-box-header
          %span.item-box-header__big-title 出品画像
          %span.item-box-header__must-icon 必須
        .item-image__infomation
          最大10枚までアップロードできます
        .item-image__uploadarea
          = f.file_field :avatar, style: "display: none", class: "image-upload", id: "image-upload"
          .item-image__uploadarea-text{onClick: "$('#image-upload').click();"}
            %p.image-message ドラッグアンドドロップ
            %p.image-message またはクリックしてファイルをアップロード

      // 商品名
      .item-data.box
        .item-box-header
          %span.item-box-header__small-title 商品名
          %span.item-box-header__must-icon 必須
        = f.text_field :name, class: "item-data__name text-field", placeholder: "商品名(必須 40文字まで)"
        .item-box-header__next
          %span.item-box-header__small-title 商品説明
          %span.item-box-header__must-icon 必須
        = f.text_area :description, class: "item-data__detail text-area", placeholder: "商品の説明（1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

      // 商品の詳細
      .item-detail.box.flexbox
        .left-side 商品の詳細
        .right-side
          .item-box-header
            %span.item-box-header__small-title カテゴリー
            %span.item-box-header__must-icon 必須
          = f.select :category_id, [ 1, 2, 3, 4], {}, {class: "item-detail__category select-field"}
          .item-box-header__next
            %span.item-box-header__small-title 商品の状態
            %span.item-box-header__must-icon 必須
          = f.select :status, ["---", "新品、未使用", "未使用に近い", "目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"], {}, {class: "item-detail__status select-field"}

      // 配送詳細
      .item-delivery.box.flexbox
        .left-side 配送について
        .right-side
          .item-box-header
            %span.item-box-header__small-title 配送料の負担
            %span.item-box-header__must-icon 必須
          = f.select :delivery_charge_burden, ["---", "送料込み(出品者負担)", "着払い(購入者負担)"], {}, {class: "item-delivery__fee select-field"}
          .item-box-header__next
            %span.item-box-header__small-title 発送元の地域
            %span.item-box-header__must-icon 必須
          = f.select :prefecture, ["---", "ここは後日active_hash"], {}, {class: "item-delivary__area select-field"}
          .item-box-header__next
            %span.item-box-header__small-title 発送までの日数
            %span.item-box-header__must-icon 必須
          = f.select :days_up_to_delivery, ["---","1〜2日で発送","2〜3日で発送","4〜7日で発送"], {}, {class: "item-delivary__days select-field"}
      // 料金
      .item-price.box.flexbox
        .left-side
          %span 販売価格(300〜9,999,999)
          %span.fas.fa-question-circle.blue-icon
        .right-side
          .right-side-first.flexbox.pad-1
            .right-side-left
              .item-box-header
                %span.item-box-header__small-title 価格
                %span.item-box-header__must-icon 必須
            .right-side-right
              %span.yen-mark ¥
              = f.text_field :price, placeholder: "例）300", class: "item-price__sell text-field text-field__mini"
          .right-side-second.flexbox.pad-2.bar
            .right-side-left
              %p.fee 販売手数料(10%)
            .right-side-right
              .show-tax -
          .right-side-third.flexbox.pad-2.bar
            .right-side-left
              %p.profit.bold 販売利益
            .right-side-right
              .show-profit.bold -

      // 注意書きと出品ボタン
      .attention.box
        .attention-text
          .attention
            %p.attention-1
              = link_to "禁止されている出品", "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/", class: "no-line"
              、
              = link_to "行為", "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/", class: "no-line"
              を必ずご確認ください。
            %p.attention-2
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "偽ブランドの販売", "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/", class: "no-line"
              は犯罪であり処罰される可能性があります。
            %p.attention-3
              また、出品をもちまして
              = link_to "加盟店規約", "https://www.mercari.com/jp/seller_terms/", class: "no-line"
              に同意したことになります。
        = f.submit "出品する", class: "listing-btn"
        .return-area
          = link_to 'もどる','/',class: "return-btn"


  = render "/registrations/registration-footer"

app/views/items/purchase_confirmation.html.haml
.main-content
  = render "/registrations/registration-header"

  .confirmation
    .confirmation__header
      購入を確定しますか？
    .confirmation__container
      = image_tag "https://www.apollon-tcg.jp/data/apollon/product/15ay/15aybrep1.jpg",size: "148x148", class: "confirmation__img"
      .confirmation__item-title
        オベリスクの巨神兵
    .confirmation__container__buy-price
      .confirmation__pay
        ¥2,500
      .confirmation__post-margin
        送料込み
    .confirmation__point
      ポイントはありません
    .confirmation__container__buy-price-cell
      .confirmation__pay__title
        支払い金額
      .confirmation__pay
        ¥2,500
      .confirmation__btn
        購入する

    .confirmation__delivery
      .confirmation__delivery__spot
        配送先
      .confirmation__delivery__post
        〒555-1935
      .confirmation__delivery__adress
        集英都 飛市 少年区 童実野町 海馬コーポレーション
      .confirmation__delivery__name
        海馬瀬人
      .confirmation__change{hover: "$('#confirmation__change').hover();"}
        = link_to "変更する","", class: "confirmation__change", id: "confirmation__change"

    .confirmation__payment-method
      .confirmation__payment-method__spot
        支払方法
      .confirmation__payment-method__card-number
        *********5355
      .confirmation__payment-method__expiration_date
        03/23
      .confirmation__payment-method__image
        = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2845599746",size: "49x15", class: "img"
      .confirmation__change{hover: "$('#confirmation__change').hover();"}
        = link_to "変更する","", class: "confirmation__change"

  = render "/registrations/registration-footer"

app/views/items/show.html.haml
= render 'header'
= render 'breadcrumbs-item'

.pickup_show
  = render partial: 'individual'

  .comment-container
    .comment-container__box
      .comment-container__box__icon
        = image_tag "top_image/user-icon.svg"
        .comment-container__box__body
          安くしてください
          %i.far.fa-clock
            5日前

      .comment-container__box__icon
        = image_tag "top_image/user-icon.svg"
        .comment-container__box__body
          安くしてください
          %i.far.fa-clock
            5日前

      .comment-container__box__icon
        = image_tag "top_image/user-icon.svg"
        .comment-container__box__body
          安くしてください
          %i.far.fa-clock
            5日前

      %p.comment 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .comment-container__box__comment
        %textarea.comment-cantainer__box__comment{:cols => "50", :name => "example", :rows => "10"}
      .comment-container__box__button コメントする
  .link_prev_next
    .link_prev 前に戻る
    .link_next 次に進む
  .item_social_media_box
    %i.fab.fa-facebook-square
    %i.fab.fa-twitter-square
    %i.fab.fa-pinterest-square

  .user_others__items
    #{@item.user.profile.name}さんのその他の出品
  .new_pickup__category__individual_new
    - @others.each do |other|
      = link_to item_path(other.id), class: "new_pickup__category__new__contents_box" do
        .contents_image_box
          - if other.trade.present?
            .contents_image_box--redTryangle
              .contents_image_box--redTryangle__textSold sold
          = image_tag other.avatar, class: "subShowImg"
        .itemBoxBody
          .itemBoxBody__name
            = other.name
          .itemBoxBody__num
            .itemBoxBody__num__price ¥ #{ other.price.to_s(:delimited) }
            .itemBoxBody__num__tax (税込)
            %i.far.fa-heart 4


  .user_others__items
    #{@item.category_id}のその他の商品
  .new_pickup__category__individual_new
    - @others.each do |other|
      =link_to  item_path(other.id), class: "new_pickup__category__new__contents_box" do
        .contents_image_box
          - if other.trade.present?
            .contents_image_box--redTryangle
              .contents_image_box--redTryangle__textSold sold
          = image_tag other.avatar, class: "subShowImg"
        .itemBoxBody
          .itemBoxBody__name
            = other.name
          .itemBoxBody__num
            .itemBoxBody__num__price ¥ #{ other.price.to_s(:delimited) }
            .itemBoxBody__num__tax (税込)
            %i.far.fa-heart 4

= render 'footer'

app/views/items/update.html.haml
.contents.row
  .success
    %h3
      更新が完了しました。
    = link_to item_path do
      .modoru
        出品詳細画面へ戻る